#!/usr/bin/env php
<?php
/**
 * Console应用入口
 * Created by PhpStorm.
 * @package void
 * @version 16/3/16 下午5:13
 * @author cbwfree
 */

// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');

// 加载框架引导文件
require __DIR__ . '/framework/console.php';